// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ps7-btZSzta1V7043ZNZ9ShEZ4Kus_8',
    appId: '1:357968196718:web:a68f74040a40bc102fa27f',
    messagingSenderId: '357968196718',
    projectId: 'fir-account1-541c4',
    authDomain: 'fir-account1-541c4.firebaseapp.com',
    databaseURL: 'https://fir-account1-541c4-default-rtdb.firebaseio.com',
    storageBucket: 'fir-account1-541c4.appspot.com',
    measurementId: 'G-JXS2W0NL1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvKMvC3Uq3ISj-L5MnragFR6E8BXTxrV4',
    appId: '1:357968196718:android:8940bb3c5d4383102fa27f',
    messagingSenderId: '357968196718',
    projectId: 'fir-account1-541c4',
    databaseURL: 'https://fir-account1-541c4-default-rtdb.firebaseio.com',
    storageBucket: 'fir-account1-541c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVWCwvXmzQexQgBak0mCAYpa_l04aOnYI',
    appId: '1:357968196718:ios:396302cd77a5a9462fa27f',
    messagingSenderId: '357968196718',
    projectId: 'fir-account1-541c4',
    databaseURL: 'https://fir-account1-541c4-default-rtdb.firebaseio.com',
    storageBucket: 'fir-account1-541c4.appspot.com',
    iosBundleId: 'com.example.firebaseAccount1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVWCwvXmzQexQgBak0mCAYpa_l04aOnYI',
    appId: '1:357968196718:ios:9143e34972f5c6ae2fa27f',
    messagingSenderId: '357968196718',
    projectId: 'fir-account1-541c4',
    databaseURL: 'https://fir-account1-541c4-default-rtdb.firebaseio.com',
    storageBucket: 'fir-account1-541c4.appspot.com',
    iosBundleId: 'com.example.firebaseAccount1.RunnerTests',
  );
}
